export const TEXT = {
    privacyPolicy: 'Политика конфиденциальности',
    email: 'Email',
    password: 'Пароль',
    enter: 'Войти',
    save: 'Сохранить',
    edit: 'Редактировать',
    register: 'Зарегистрироваться',
    forgetPassword: 'Забыли пароль',
    delete: 'Удалить',
    cancel: 'Отмена',
    show: 'Показать',

    registration: 'Регистрация',
    of: 'из',
    next: 'Далее',
    back: 'Назад',
    profile: 'Профиль',
    private: 'Личный',
    business: 'Бизнес',
    whatAccountNeed: 'Какой аккаунт вы хотите создать',

    name: 'Имя',
    fillRegistrationForm: 'Заполните форму регистрации',
    approveText: 'Нажимая кнопку "Зарегистрироваться", вы подтверждаете, что принимаете наши',
    conditions: 'Условия использования',
    and: 'и',
    privacyPolicyObjectiveCase: 'Политику конфиденциальности',

    myOrders: 'Мои заказы',
    myAddresses: 'Мои адреса',
    myCards: 'Мои карты',
    messages: 'Сообщения',
    notifications: 'Уведомления',
    support: 'Служба поддержки',
    settings: 'Настройки',
    logout: 'Выйти',

    emptyUserAddressList:
        'Пока нет ни одного адреса в списке.\n' + 'Добавьте адрес доставки через иконку «+»',
    emptyUserCardList: 'Пока нет ни одной карты в списке.\n' + 'Добавьте карту оплаты через иконку «+»',
    emptyNotificationList: 'Пока нет уведомлений',
    emptyMessageList: 'Пока нет сообщений',
    addAddress: 'Добавить адрес',
    addCard: 'Добавить карту',
    editAddress: 'Редактировать адрес',

    questionMark: '?',

    country: 'Страна',
    region: 'Регион',
    city: 'Город',
    street: 'Улица',
    index:'Индекс',
    firstName: 'Фамилия',
    house: 'Дом',
    building: 'Корпус',
    block: 'Строение',
    apartment: 'Квартира',
    code: 'Код',
    phoneNumber: 'Номер телефона',

    cardNumber: 'Номер карты',
    cardHolderName: 'Имя и фамилия держателя карты(латиница)',
    month: 'Месяц',
    year: 'Год',
    cvc: 'CVC',

    cardListToPay: 'Принимаются к оплате Maestro, Mastercard, Visa, МИР',
    paymentProtection: 'Платеж защищен PCI DSS',

    changePassword: 'Изменить пароль',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    repeatNewPassword: 'Повторите пароль',
    notEqualPasswordError: 'Введенные пароли не совпадают',

    supportMessage: 'Здравствуйте! У вас возник вопрос?',

    fieldNotBeEmpty: 'Введите',

    deleteAddress: 'Удалить адрес',
    areYouSureToDeleteAddress: 'Вы уверены, что хотите удалить этот адрес?',

    deleteCard: 'Удалить карту',
    areYouSureToDeleteCard: 'Вы уверены, что хотите удалить эту карту?',

    accountExit: 'Выйти из аккаунта',
    areYouSureToExit: 'Вы уверены, что хотите выйти?',

    today: 'Сегодня',
    sevenDays: 'За 7 дней',
    thirtyDays: 'За 30 дней',

    message: 'Сообщение',

    welcome: 'Добро пожаловать в Flosty',
    doSubscribe: 'Подписывайтесь на интересные вам магазины, чтобы видеть товары, которые они публикуют. Также вы можете настроить персональную подписку в соответствии с вашими вкусами',
    subscribe: 'Подписаться',
    writeToVendor: 'Написать продавцу',
    search: 'Поиск ',
    filter: 'Фильтр',

    filters: 'Фильтры',

    sorting: 'Сортировка',
    increase: 'По возрастающей цене',
    decrease: 'По убывающей цене',
    new: 'По новизне',
    rating: 'По рейтингу',

    price: 'Цена',
    from: 'от',
    till: 'до',

    category: 'Категория',

    footWear: 'Обувь',
    ballerinas: 'Балетки',
    slippers: 'Домашние тапочки',
    boots: 'Ботинки',
    sandals: 'Босоножки',
    gumshoes: 'Кеды',
    sneakers: 'Кроссовки',
    loafers: 'Лоферы',
    moccasins: 'Мокасины',
    lowShoes: 'Полуботинки',
    highBoots: 'Сапоги',
    shoes: 'Туфли',

    clothes: 'Одежда',
    shirts: 'Блузки и рубашки',
    costumes: 'Костюмы',
    skirts: 'Юбки',
    trouthers: 'Брюки',
    tShirts: 'Футболки и топы',
    sweaters: 'Свитера и кардиганы',
    dresses: 'Платья и сарафаны',
    jackets: 'Пиджаки',
    overall: 'Комбинезон',
    homeWear: 'Одежда для сна и отдыха',

    accessorises: 'Аксессуары',
    hats: 'Головные уборы',
    socks: 'Носки, чулки, колготки',
    scarves: 'Шарфы и платки',

    season: 'Сезон',
    winter: 'Зима',
    summer: 'Лето',
    fall: 'Осень',
    spring: 'Весна',

    default: 'По умолчанию',
    allCategories: 'Все категории',
    allSeasons: 'Все сезоны',
    all: 'Все в этой категории',

    electronics: 'Электроника',
    womanClothes: 'Женский гардероб',
    beauty: 'Красота и здоровье',
    bags: 'Чемоданы и сумки',
    manClothes: 'Мужской гардероб',
    jewellry: 'Украшения и бижутерия',
    homeGoods: 'Товары для дома',
    repairGoods: 'Строительство и ремонт',
    gardenGoods: 'Дача, сад, огород',
    sportGoods: 'Спорт и отдых',
    childrenGoods: 'Детские товары',
    animalGoods: 'Товары для животных',
    hobbyGoods: 'Хобби и творчество',
    paperGoods: 'Канцелярия',

};
