export const TEXT = {
    privacyPolicy: 'Политика конфиденциальности',
    email: 'Email',
    password: 'Пароль',
    enter: 'Войти',
    save: 'Сохранить',
    edit: 'Редактировать',
    register: 'Зарегистрироваться',
    forgetPassword: 'Забыли пароль',
    delete: 'Удалить',
    cancel: 'Отмена',
    show: 'Показать',
    favorite: 'Избранное',
    buyFor: 'Купить за ',
    rubleSign: '₽',

    registration: 'Регистрация',
    of: 'из',
    next: 'Далее',
    back: 'Назад',
    profile: 'Профиль',
    private: 'Личный',
    business: 'Бизнес',
    whatAccountNeed: 'Какой аккаунт вы хотите создать',

    name: 'Имя',
    fillRegistrationForm: 'Заполните форму регистрации',
    approveText: 'Нажимая кнопку "Зарегистрироваться", вы подтверждаете, что принимаете наши',
    conditions: 'Условия использования',
    and: 'и',
    privacyPolicyObjectiveCase: 'Политику конфиденциальности',

    myOrders: 'Мои заказы',
    myAddresses: 'Мои адреса',
    myCards: 'Мои карты',
    messages: 'Сообщения',
    notifications: 'Уведомления',
    support: 'Служба поддержки',
    settings: 'Настройки',
    logout: 'Выйти',

    emptyUserAddressList:
        'Пока нет ни одного адреса в списке.\n' + 'Добавьте адрес доставки через иконку «+»',
    emptyUserCardList: 'Пока нет ни одной карты в списке.\n' + 'Добавьте карту оплаты через иконку «+»',
    emptyNotificationList: 'Пока нет уведомлений',
    emptyMessageList: 'Пока нет сообщений',
    emptyFavoriteList: 'Вам пока ничего не приглянулось. Но это не поздно исправить прямо сейчас!',
    addAddress: 'Добавить адрес',
    addCard: 'Добавить карту',
    editAddress: 'Редактировать адрес',

    questionMark: '?',

    country: 'Страна',
    region: 'Регион',
    city: 'Город',
    street: 'Улица',
    index:'Индекс',
    firstName: 'Фамилия',
    house: 'Дом',
    building: 'Корпус',
    block: 'Строение',
    apartment: 'Квартира',
    code: 'Код',
    phoneNumber: 'Номер телефона',

    cardNumber: 'Номер карты',
    cardHolderName: 'Имя и фамилия держателя карты(латиница)',
    month: 'Месяц',
    year: 'Год',
    cvc: 'CVC',

    cardListToPay: 'Принимаются к оплате Maestro, Mastercard, Visa, МИР',
    paymentProtection: 'Платеж защищен PCI DSS',

    changePassword: 'Изменить пароль',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    repeatNewPassword: 'Повторите пароль',
    notEqualPasswordError: 'Введенные пароли не совпадают',

    supportMessage: 'Здравствуйте! У вас возник вопрос?',

    fieldNotBeEmpty: 'Введите',

    deleteAddress: 'Удалить адрес',
    areYouSureToDeleteAddress: 'Вы уверены, что хотите удалить этот адрес?',

    deleteCard: 'Удалить карту',
    areYouSureToDeleteCard: 'Вы уверены, что хотите удалить эту карту?',

    accountExit: 'Выйти из аккаунта',
    areYouSureToExit: 'Вы уверены, что хотите выйти?',

    today: 'Сегодня',
    sevenDays: 'За 7 дней',
    thirtyDays: 'За 30 дней',

    message: 'Сообщение',

    welcome: 'Добро пожаловать в Flosty',
    doSubscribe: 'Подписывайтесь на интересные вам магазины, чтобы видеть товары, которые они публикуют. Также вы можете настроить персональную подписку в соответствии с вашими вкусами',
    subscribe: 'Подписаться',
    unsubscribe: 'Отписаться',
    adjustSubscription: 'Детализировать подписку',
    writeToVendor: 'Написать продавцу',
    search: 'Поиск ',
    filter: 'Фильтр',

    filters: 'Фильтры',

    sorting: 'Сортировка',
    increase: 'По возрастающей цене',
    decrease: 'По убывающей цене',
    new: 'По новизне',
    rating: 'По рейтингу',

    price: 'Цена',
    from: 'от',
    till: 'до',

    category: 'Категория',

    footWear: 'Обувь',
    ballerinas: 'Балетки',
    slippers: 'Домашние тапочки',
    boots: 'Ботинки',
    sandals: 'Босоножки',
    gumshoes: 'Кеды',
    sneakers: 'Кроссовки',
    loafers: 'Лоферы',
    moccasins: 'Мокасины',
    lowShoes: 'Полуботинки',
    highBoots: 'Сапоги',
    shoes: 'Туфли',
    flipFlops: 'Сандали и вьетнамки',
    mules: 'Женские мюли',
    footWearAccessorises: 'Аксессуары для обуви',

    clothes: 'Одежда',
    shirts: 'Блузки и рубашки',
    costumes: 'Костюмы',
    skirts: 'Юбки',
    trouthers: 'Брюки',
    tShirts: 'Футболки и топы',
    sweaters: 'Свитера и кардиганы',
    dresses: 'Платья и сарафаны',
    jackets: 'Пиджаки',
    overalls: 'Комбинезоны',
    homeWear: 'Одежда для сна и отдыха',
    underwear: 'Нижнее белье',
    swimSuits: 'Купальники и пляжная одежда',
    coats: 'Пальто и куртки',
    sleepWear: 'Одежда для сна и отдыха',
    sportWear: 'Спортивная одежда',
    suits: 'Костюмы',
    shorts: 'Шорты',
    pregnantClothes: 'Одежда для беременных',
    weddingClothes: 'Одежда на свадьбу',
    jacketsAndWraps: 'Жакеты и накидки',
    weddingAccessorises: 'Свадебные аксессуары',
    partyClothes: 'Одежда на костюмированную вечеринку',


    accessorises: 'Аксессуары',
    hats: 'Головные уборы',
    socks: 'Носки, чулки, колготки',
    scarves: 'Шарфы и платки',
    coinBags: 'Монетницы и брелоки',
    glasssesAndAccessorises: 'Очки и аксессуары',
    belts: 'Ремни и пояса',
    hairAccessorises: 'Аксессуары для волос',
    watches: 'Часы и аксессуары',
    gloves: 'Перчатки и варежки',
    fans: 'Веера',
    umbrellas: 'Зонты и дождевики',

    season: 'Сезон',
    winter: 'Зима',
    summer: 'Лето',
    fall: 'Осень',
    spring: 'Весна',

    default: 'По умолчанию',
    allCategories: 'Все категории',
    allSeasons: 'Все сезоны',
    all: 'Все в этой категории',

    electronics: 'Электроника',
    womanClothes: 'Женский гардероб',
    beauty: 'Красота и здоровье',
    bagsAndCases: 'Чемоданы и сумки',
    manClothes: 'Мужской гардероб',
    jewellry: 'Украшения и бижутерия',
    homeGoods: 'Товары для дома',
    repairGoods: 'Строительство и ремонт',
    gardenGoods: 'Дача, сад, огород',
    sportGoods: 'Спорт и отдых',
    childrenGoods: 'Детские товары',
    animalGoods: 'Товары для животных',
    hobbyGoods: 'Хобби и творчество',
    paperGoods: 'Канцелярия',

    phones: 'Телефоны и аксессуары',
    mobilePhones: 'Мобильные телефоны',
    phoneAccessorises: 'Аксессуары для телефонов',
    phoneCases: 'Чехлы и сумки',
    phoneGlasses: 'Пленки и стекла',
    phoneSpares: 'Ремонт и запасные части',
    radioSets: 'Рации и аксессуары',
    stationPhones: 'Домашние и офисные телефоны',

    audioAndVideo: 'Аудио- и видеотехника',
    earPhones: 'Наушники',
    audioDevices: 'Аудиотехника',
    tvDevices: 'ТВ-оборудование',
    audioAndVideoAccessorises: 'Аксессуары для аудио- и видеотехники',
    projectors: 'Проекторы',

    smartElectronics: 'Смарт-электроника',
    smartWatches: 'Смарт-часы',
    smartBracelets: 'Фитнес-трекеры и смарт-браслеты',
    smartAccessorises: 'Аксессуары для часов и трекеров',
    smartRings: 'Смарт-кольца',

    computers: 'Компьютерная техника',
    stationComputers: 'Стационарные компьютеры',
    laptops: 'Ноутбуки',
    tablets: 'Планшеты',
    computerParts: 'Компьютерные комплектующие',
    computerAccessorises: 'Компьютерные аксессуары',
    officeEquipment: 'Оргтехника',
    network: 'Сеть',

    memory: 'Накопители данных',
    usb: 'USB-флешки',
    sticks: 'Карты памяти',
    discs: 'Жеские диски и аксессуары',
    readers: 'Кардридеры',
    discEmulators: 'Эмуляторы дисков',
    memoryAccessorises: 'Аксессуары для накопителей данных',

    electricalGoods: 'Бытовая техника',
    kitchen: 'Кухонная техника',
    cleaning: 'Техника для уборки',
    climate: 'Климатическая техника',
    electricalSpares: 'Запасные части для бытовой техники',
    smartHome: 'Умный дом',
    clothesDevices: 'Техника для ухода за одеждой',
    beautyDevices: 'Техника для красоты и здоровья',

    cameras: 'Фото- и видеокамеры',
    videoCameras: 'Видеокамеры',
    photoCameras: 'Фотоаппараты',
    drones: 'Дроны и запчасти',
    frames: 'Цифровые фоторамки',
    cameraAccessorises: 'Аксессуары для фото- и видеокамер',
    cameraSpares: 'Запасные части для камер',

    gameConsoles: 'Игровые приставки',
    PlayStation: 'PlayStation',
    XBOX: 'XBOX',
    Nintendo: 'Nintendo Co.',
    glasses: 'Очки виртуальной реальности',
    danceRags: 'Танцевальные коврики',
    controllers: 'Контроллеры',

    opticalGoods: 'Оптические приборы',
    hunt: 'Охотничья оптика',
    endoscopes: 'Эндоскопы',
    magnifiers: 'Лупы',
    telescopes: 'Телескопы',
    microscopes: 'Микроспопы',
    prisms: 'Призмы',

    bags: 'Сумки',
    crossBodyBags: 'Сумки через плечо',
    shortHandleBags: 'Сумки с короткими ручками',
    wallets: 'Кошельки',
    womanBackPacks: 'Женские рюкзаки',
    shoulderBags: 'Сумки на плечо',
    bigBags: 'Вместительные сумки',
    waistBags: 'Сумки на пояс',
    clutches: 'Клатчи',
    bagBags: 'Сумки-мешки',
    wristBags: 'Сумки-напульсники',
    bagsAccessorises: 'Аксессуары для сумок',

    garmentCare: 'Уход за одеждой',
    hangers: 'Вешалки',
    spoolRemovals: 'Машинки для удаления катышков',
    stickyRollers: 'Липкие ролики и щетки',
    foldingBoards: 'Доски для складывания',

    nails: 'Маникюр и педикюр',
    makeUp: 'Макияж',
    skinCare: 'Уход за кожей',
    shaving: 'Бритье и удаление волос',
    hairCare: 'Уход за волосами и укладка',
    wigs: 'Наращивание волос и парики',
    perfumery: 'Парфюмерия',
    tatoos: 'Татуировки и боди-арт',
    beautySalonProducts: 'Товары для салонов красоты',

    bought: 'купили',
    saved: 'сохранили',

    tags: 'Теги',

    pickColor: 'Выберите цвет',
    pickSize: 'Выберите размер',
    color: 'Цвет',
    size: 'Размер',

    red: 'красный',
    green: 'зеленый',
    blue: 'синий',
    yellow: 'желтый',
    orange: 'оранжевый',
    gold: 'золотой',
    silver: 'серебряный',
    black: 'черный',
    grey: 'серый',
    white: 'белый',

    productDescription: 'Описание товара',
    delivery: 'Доставка',
    free: 'Бесплатно',
    guarantee: 'Гарантия',
    flostyGuaranteeTitle: 'Flosty всегда на стороне покупателя!',
    returnMoneyTime: 'Мы вернем деньги,  если товар не доставлен в течение 14 рабочих дней после оплаты. У вас есть 2 недели для подачи заявки на возврат.',
    wrongDescription: 'Товар  не соответствует описанию? Напишите нам в течение 14 дней после получения!',
    returnMoneyOnCount: 'В случае отмены деньгии поступят на счет в течение 14 дней.',

    findSomethingToSubscribe: 'Найдите, на что хотите подписаться',
    subscribeToFollow: 'Подписывайтесь на магазины в Flosty и следите за их  обновлениями',
    subscriptions: 'Подписки',
    subscription: 'Подписка',
    feed: 'Лента',
    history: 'История',
    shop: 'магазин',
    shopWithCapital: 'Магазин',

    allTags: 'Все',
    shops: 'Магазины',
    adjusted: 'Настраиваемые',
    subscriptionAdjustment: 'Детализация подписки',
    youChoose: 'Вы выбрали',
    findYouNeed: 'Найдите необходимое',
    youAlsoLike: 'Возможно, вам еще понравится',
};
