export enum UserAction {
    USER_SET_USER = 'UserSetUser',
    USER_SET_ADDRESS_LIST = 'UserSetAddressList',
    USER_SET_CARD_LIST = 'UserSetCardList',
    USER_ADD_ADDRESS = 'UserAddAddress',
    USER_SET_ORDER_LIST = 'UserSetOrderList',
    USER_DELETE_ADDRESS = 'UserDeleteAddress',
    USER_ADD_CARD = 'UserAddCard',
    USER_DELETE_CARD = 'UserDeleteCard',
    USER_SET_PROCESSING_DATA = 'UserSetProcessingData',
    USER_SET_IS_LOADING = 'UserSetIsLoading',
    USER_SET_NOTIFICATION_LIST = 'UserSetNotificationList',
    USER_SUPPORT_CHAT_ADD_MESSAGE = 'UserSupportChatAddMessage',
    USER_SHOP_CHAT_ADD_MESSAGE = 'UserShopChatAddMessage',
    USER_SHOP_CHAT_ADD_FIRST_MESSAGE = 'UserShopChatAddFirstMessage',
};
